# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutWindow(object):
    def setupUi(self, AboutWindow):
        AboutWindow.setObjectName("AboutWindow")
        AboutWindow.resize(580, 580)
        AboutWindow.setStyleSheet("font: 14pt \"Calibri\";\n"
"background-color: rgb(221, 221, 221);\n"
"")
        self.frame_fr_ok_btn = QtWidgets.QFrame(parent=AboutWindow)
        self.frame_fr_ok_btn.setGeometry(QtCore.QRect(12, 492, 553, 73))
        self.frame_fr_ok_btn.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.frame_fr_ok_btn.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fr_ok_btn.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fr_ok_btn.setObjectName("frame_fr_ok_btn")
        self.pushButton_ok = QtWidgets.QPushButton(parent=self.frame_fr_ok_btn)
        self.pushButton_ok.setGeometry(QtCore.QRect(416, 15, 121, 49))
        self.pushButton_ok.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(160, 160, 160);\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.frame_about_info = QtWidgets.QFrame(parent=AboutWindow)
        self.frame_about_info.setGeometry(QtCore.QRect(12, 12, 553, 457))
        self.frame_about_info.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_about_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_about_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_about_info.setObjectName("frame_about_info")

        self.retranslateUi(AboutWindow)
        QtCore.QMetaObject.connectSlotsByName(AboutWindow)

    def retranslateUi(self, AboutWindow):
        _translate = QtCore.QCoreApplication.translate
        AboutWindow.setWindowTitle(_translate("AboutWindow", "Dialog"))
        self.pushButton_ok.setText(_translate("AboutWindow", "ОК"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutWindow = QtWidgets.QDialog()
    ui = Ui_AboutWindow()
    ui.setupUi(AboutWindow)
    AboutWindow.show()
    sys.exit(app.exec())
