# Form implementation generated from reading ui file 'edit_commands.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Edit_commands(object):
    def setupUi(self, Edit_commands):
        Edit_commands.setObjectName("Edit_commands")
        Edit_commands.resize(702, 555)
        Edit_commands.setStyleSheet("font: 14pt \"Calibri\";\n"
"background-color:#F6F6F6;")
        self.frame_ok_cans = QtWidgets.QFrame(parent=Edit_commands)
        self.frame_ok_cans.setGeometry(QtCore.QRect(12, 468, 685, 80))
        self.frame_ok_cans.setStyleSheet("QFrame#frame_ok_cans{\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QPushButton {\n"
"    background-color: #E2E2E2;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D9D9D9;\n"
"}")
        self.frame_ok_cans.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ok_cans.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ok_cans.setObjectName("frame_ok_cans")
        self.pushButton_ok = QtWidgets.QPushButton(parent=self.frame_ok_cans)
        self.pushButton_ok.setEnabled(True)
        self.pushButton_ok.setGeometry(QtCore.QRect(468, 24, 97, 37))
        self.pushButton_ok.setStyleSheet("font: 9pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(parent=self.frame_ok_cans)
        self.pushButton_cancel.setGeometry(QtCore.QRect(576, 24, 97, 37))
        self.pushButton_cancel.setStyleSheet("font: 9pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.frame_command_edit = QtWidgets.QFrame(parent=Edit_commands)
        self.frame_command_edit.setGeometry(QtCore.QRect(0, 0, 709, 433))
        self.frame_command_edit.setStyleSheet("QFrame{\n"
"    background-color:#FFFFFF;\n"
"}\n"
"\n"
"Qlabel{\n"
"    background-color: rgb(236, 236, 236);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #FFFFFF;\n"
"border: solid #D9D9D9;\n"
"border-width: 1px;\n"
"border-radius: 10px;}")
        self.frame_command_edit.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_command_edit.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_command_edit.setObjectName("frame_command_edit")
        self.label_command = QtWidgets.QLabel(parent=self.frame_command_edit)
        self.label_command.setGeometry(QtCore.QRect(24, 12, 61, 25))
        self.label_command.setStyleSheet("font: 9pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.label_command.setObjectName("label_command")
        self.lineEdit_command = QtWidgets.QLineEdit(parent=self.frame_command_edit)
        self.lineEdit_command.setGeometry(QtCore.QRect(24, 36, 660, 30))
        self.lineEdit_command.setStyleSheet("")
        self.lineEdit_command.setObjectName("lineEdit_command")
        self.label_param_type = QtWidgets.QLabel(parent=self.frame_command_edit)
        self.label_param_type.setGeometry(QtCore.QRect(24, 96, 109, 25))
        self.label_param_type.setStyleSheet("font: 9pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.label_param_type.setObjectName("label_param_type")
        self.comboBox_param_type = QtWidgets.QComboBox(parent=self.frame_command_edit)
        self.comboBox_param_type.setGeometry(QtCore.QRect(24, 120, 660, 30))
        self.comboBox_param_type.setStyleSheet("")
        self.comboBox_param_type.setObjectName("comboBox_param_type")
        self.comboBox_param_type.addItem("")
        self.comboBox_param_type.addItem("")
        self.label_response = QtWidgets.QLabel(parent=self.frame_command_edit)
        self.label_response.setGeometry(QtCore.QRect(24, 180, 133, 25))
        self.label_response.setStyleSheet("font: 9pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.label_response.setObjectName("label_response")
        self.lineEdit_response = QtWidgets.QLineEdit(parent=self.frame_command_edit)
        self.lineEdit_response.setGeometry(QtCore.QRect(24, 204, 660, 30))
        self.lineEdit_response.setStyleSheet("")
        self.lineEdit_response.setObjectName("lineEdit_response")
        self.label_error = QtWidgets.QLabel(parent=self.frame_command_edit)
        self.label_error.setGeometry(QtCore.QRect(24, 264, 145, 25))
        self.label_error.setStyleSheet("font: 9pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.label_error.setObjectName("label_error")
        self.lineEdit_error = QtWidgets.QLineEdit(parent=self.frame_command_edit)
        self.lineEdit_error.setGeometry(QtCore.QRect(24, 288, 660, 30))
        self.lineEdit_error.setStyleSheet("")
        self.lineEdit_error.setObjectName("lineEdit_error")
        self.label_timeout = QtWidgets.QLabel(parent=self.frame_command_edit)
        self.label_timeout.setGeometry(QtCore.QRect(24, 360, 265, 25))
        self.label_timeout.setStyleSheet("font: 9pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.label_timeout.setObjectName("label_timeout")
        self.lineEdit_timeout = QtWidgets.QLineEdit(parent=self.frame_command_edit)
        self.lineEdit_timeout.setGeometry(QtCore.QRect(24, 384, 660, 30))
        self.lineEdit_timeout.setStyleSheet("")
        self.lineEdit_timeout.setObjectName("lineEdit_timeout")

        self.retranslateUi(Edit_commands)
        QtCore.QMetaObject.connectSlotsByName(Edit_commands)

    def retranslateUi(self, Edit_commands):
        _translate = QtCore.QCoreApplication.translate
        Edit_commands.setWindowTitle(_translate("Edit_commands", "Edit_Command"))
        self.pushButton_ok.setText(_translate("Edit_commands", "ОК"))
        self.pushButton_cancel.setText(_translate("Edit_commands", "Отмена"))
        self.label_command.setText(_translate("Edit_commands", "Команда:"))
        self.label_param_type.setText(_translate("Edit_commands", "Тип параметра:"))
        self.comboBox_param_type.setItemText(0, _translate("Edit_commands", "Целочисленный параметр"))
        self.comboBox_param_type.setItemText(1, _translate("Edit_commands", "Без параметра"))
        self.label_response.setText(_translate("Edit_commands", "Ожидаемый ответ:"))
        self.label_error.setText(_translate("Edit_commands", "Ожидаемая ошибка:"))
        self.label_timeout.setText(_translate("Edit_commands", "Максимальное время ожидания (в мс):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Edit_commands = QtWidgets.QDialog()
    ui = Ui_Edit_commands()
    ui.setupUi(Edit_commands)
    Edit_commands.show()
    sys.exit(app.exec())