
# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("font: 12pt \"intel\";\n"
"background-color:#F6F6F6;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    background-color: #E2E2E2;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.clear_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(1164, 204, 80, 80))
        self.clear_button.setStyleSheet("color: rgb(0, 0, 0);")
        self.clear_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/clear_all.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clear_button.setIcon(icon)
        self.clear_button.setObjectName("clear_button")
        self.export_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.export_button.setGeometry(QtCore.QRect(1164, 300, 80, 80))
        self.export_button.setStyleSheet("color: rgb(0, 0, 0);")
        self.export_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.export_button.setIcon(icon1)
        self.export_button.setObjectName("export_button")
        self.help_list_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.help_list_button.setGeometry(QtCore.QRect(1164, 396, 80, 80))
        self.help_list_button.setStyleSheet("color: rgb(0, 0, 0);")
        self.help_list_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/help.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.help_list_button.setIcon(icon2)
        self.help_list_button.setObjectName("help_list_button")
        self.settings_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.settings_button.setGeometry(QtCore.QRect(1164, 492, 80, 80))
        self.settings_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.settings_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_button.setIcon(icon3)
        self.settings_button.setObjectName("settings_button")
        self.listView_action = QtWidgets.QListView(parent=self.centralwidget)
        self.listView_action.setGeometry(QtCore.QRect(12, 12, 1129, 565))
        self.listView_action.setStyleSheet("background-color:#FFFFFF;\n"
"border: solid #D9D9D9;\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.listView_action.setObjectName("listView_action")
        self.frame_emulator_control = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_emulator_control.setGeometry(QtCore.QRect(12, 600, 1261, 109))
        self.frame_emulator_control.setStyleSheet("QFrame#frame_emulator_control{background-color: #FFFFFF;}\n"
"\n"
"")
        self.frame_emulator_control.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_emulator_control.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_emulator_control.setObjectName("frame_emulator_control")
        self.stop_button = QtWidgets.QPushButton(parent=self.frame_emulator_control)
        self.stop_button.setGeometry(QtCore.QRect(1056, 17, 200, 73))
        self.stop_button.setStyleSheet("color: rgb(0, 0, 0);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/stop.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stop_button.setIcon(icon4)
        self.stop_button.setObjectName("stop_button")
        self.launch_button = QtWidgets.QPushButton(parent=self.frame_emulator_control)
        self.launch_button.setGeometry(QtCore.QRect(840, 17, 200, 73))
        self.launch_button.setStyleSheet("color: rgb(0, 0, 0);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.launch_button.setIcon(icon5)
        self.launch_button.setObjectName("launch_button")
        self.profiles_combobox = QtWidgets.QComboBox(parent=self.frame_emulator_control)
        self.profiles_combobox.setGeometry(QtCore.QRect(12, 36, 265, 37))
        self.profiles_combobox.setStyleSheet("background-color: #E2E2E2;\n"
"color: rgb(0, 0, 0);\n"
"border: solid #D9D9D9;\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.profiles_combobox.setObjectName("profiles_combobox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop_button.setText(_translate("MainWindow", "Остановить"))
        self.launch_button.setText(_translate("MainWindow", "Запустить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())