# Form implementation generated from reading ui file 'settingsprofilesports.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(1280, 719)
        Settings.setStyleSheet("font: 14pt \"intel\";\n"
"background-color: #F6F6F6;")
        self.centralwidget = QtWidgets.QWidget(parent=Settings)
        self.centralwidget.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"\n"
"QPushButton {\n"
"    background-color: #E2E2E2;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D9D9D9;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1280, 613))
        self.tabWidget.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: #FFFFFF;")
        self.tabWidget.setObjectName("tabWidget")
        self.settings_profiles = QtWidgets.QWidget()
        self.settings_profiles.setStyleSheet("")
        self.settings_profiles.setObjectName("settings_profiles")
        self.frame_profiles_control = QtWidgets.QFrame(parent=self.settings_profiles)
        self.frame_profiles_control.setGeometry(QtCore.QRect(12, 12, 1249, 541))
        self.frame_profiles_control.setStyleSheet("QFrame{\n"
"    background-color:#FFFFFF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #E2E2E2;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D9D9D9;\n"
"}")
        self.frame_profiles_control.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_profiles_control.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_profiles_control.setObjectName("frame_profiles_control")
        self.add_profile_button = QtWidgets.QPushButton(parent=self.frame_profiles_control)
        self.add_profile_button.setGeometry(QtCore.QRect(972, 24, 125, 50))
        self.add_profile_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_profile_button.setIcon(icon)
        self.add_profile_button.setIconSize(QtCore.QSize(30, 30))
        self.add_profile_button.setObjectName("add_profile_button")
        self.import_profiles_button = QtWidgets.QPushButton(parent=self.frame_profiles_control)
        self.import_profiles_button.setGeometry(QtCore.QRect(1104, 24, 125, 50))
        self.import_profiles_button.setStyleSheet("color: rgb(0, 0, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/download.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.import_profiles_button.setIcon(icon1)
        self.import_profiles_button.setIconSize(QtCore.QSize(30, 30))
        self.import_profiles_button.setObjectName("import_profiles_button")
        self.listView_profiles = QtWidgets.QListView(parent=self.frame_profiles_control)
        self.listView_profiles.setGeometry(QtCore.QRect(12, 84, 1225, 445))
        self.listView_profiles.setStyleSheet("background-color: #FFFFFF;\n"
"border: solid #D9D9D9;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Calibri\";")
        self.listView_profiles.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked)
        self.listView_profiles.setDragDropOverwriteMode(False)
        self.listView_profiles.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.NoDragDrop)
        self.listView_profiles.setDefaultDropAction(QtCore.Qt.DropAction.CopyAction)
        self.listView_profiles.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.listView_profiles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.listView_profiles.setObjectName("listView_profiles")
        self.label_profile_control = QtWidgets.QLabel(parent=self.frame_profiles_control)
        self.label_profile_control.setGeometry(QtCore.QRect(24, 0, 169, 25))
        self.label_profile_control.setStyleSheet("font: 9pt \"Calibri\";\n"
"color: rgb(0, 0, 0);")
        self.label_profile_control.setObjectName("label_profile_control")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.frame_profiles_control)
        self.lineEdit_search.setGeometry(QtCore.QRect(16, 36, 241, 37))
        self.lineEdit_search.setStyleSheet("background-color: #FFFFFF;\n"
"border: solid #D9D9D9;\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.tabWidget.addTab(self.settings_profiles, "")
        self.settings_ports = QtWidgets.QWidget()
        self.settings_ports.setObjectName("settings_ports")
        self.frame_ports = QtWidgets.QFrame(parent=self.settings_ports)
        self.frame_ports.setGeometry(QtCore.QRect(12, 24, 1237, 205))
        self.frame_ports.setStyleSheet("QFrame#frame_ports{\n"
"    background-color: #FFFFFF;\n"
"    border: solid #D9D9D9;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    background-color: rgb(236, 236, 236);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #E2E2E2;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D9D9D9;\n"
"}")
        self.frame_ports.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ports.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ports.setObjectName("frame_ports")
        self.label_data_accept = QtWidgets.QLabel(parent=self.frame_ports)
        self.label_data_accept.setGeometry(QtCore.QRect(24, 12, 157, 37))
        self.label_data_accept.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label_data_accept.setObjectName("label_data_accept")
        self.label_port = QtWidgets.QLabel(parent=self.frame_ports)
        self.label_port.setGeometry(QtCore.QRect(24, 72, 61, 37))
        self.label_port.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label_port.setObjectName("label_port")
        self.comboBox_ports = QtWidgets.QComboBox(parent=self.frame_ports)
        self.comboBox_ports.setGeometry(QtCore.QRect(168, 69, 265, 37))
        self.comboBox_ports.setStyleSheet("background-color: #E2E2E2;\n"
"background-color: #FFFFFF;\n"
"border: solid #D9D9D9;\n"
"border-width: 2px;\n"
"border-radius: 10px;")
        self.comboBox_ports.setObjectName("comboBox_ports")
        self.update_COM_ports = QtWidgets.QPushButton(parent=self.frame_ports)
        self.update_COM_ports.setGeometry(QtCore.QRect(24, 132, 170, 50))
        self.update_COM_ports.setStyleSheet("color: rgb(0, 0, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/reset.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.update_COM_ports.setIcon(icon2)
        self.update_COM_ports.setIconSize(QtCore.QSize(30, 30))
        self.update_COM_ports.setObjectName("update_COM_ports")
        self.tabWidget.addTab(self.settings_ports, "")
        self.frame_ok_canc = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_ok_canc.setGeometry(QtCore.QRect(12, 624, 1261, 80))
        self.frame_ok_canc.setStyleSheet("QFrame#frame_ok_canc{\n"
"    background-color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #E2E2E2;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D9D9D9;\n"
"}")
        self.frame_ok_canc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ok_canc.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ok_canc.setObjectName("frame_ok_canc")
        self.ok_button = QtWidgets.QPushButton(parent=self.frame_ok_canc)
        self.ok_button.setGeometry(QtCore.QRect(936, 12, 150, 50))
        self.ok_button.setStyleSheet("color: rgb(0, 0, 0);")
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(parent=self.frame_ok_canc)
        self.cancel_button.setGeometry(QtCore.QRect(1104, 12, 150, 50))
        self.cancel_button.setStyleSheet("color: rgb(0, 0, 0);")
        self.cancel_button.setObjectName("cancel_button")
        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки"))
        self.add_profile_button.setText(_translate("Settings", "Добавить"))
        self.import_profiles_button.setText(_translate("Settings", "Импорт"))
        self.label_profile_control.setText(_translate("Settings", "<html><head/><body><p><span style=\" font-weight:600;\">Управление профилями</span></p></body></html>"))
        self.lineEdit_search.setInputMask(_translate("Settings", "Поиск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_profiles), _translate("Settings", "Профили"))
        self.label_data_accept.setText(_translate("Settings", "Приём данных"))
        self.label_port.setText(_translate("Settings", "Порт: "))
        self.update_COM_ports.setText(_translate("Settings", "Обновить порты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_ports), _translate("Settings", "Приём данных"))
        self.ok_button.setText(_translate("Settings", "ОК"))
        self.cancel_button.setText(_translate("Settings", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QMainWindow()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec())
